language: php

matrix:
  include:
  - php: 7.2
  - php: 7.3
  - php: nightly
  allow_failures:
  # 7.3 fails for a reason i cannot identify yet? probably xdebug or phpunit...
  - php: 7.3
  - php: nightly

before_script: travis_retry composer install --no-interaction --prefer-source
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml
after_script: bash <(curl -s https://codecov.io/bash)
